-- 문제 링크: https://programmers.co.kr/learn/courses/30/lessons/59412

WITH RECURSIVE HOURS AS (
    SELECT 9 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 19
)

SELECT HOUR, COUNT(HOUR(DATETIME)) AS `COUNT`
FROM HOURS
LEFT JOIN ANIMAL_OUTS ON HOUR(DATETIME) = HOUR
GROUP BY HOUR
ORDER BY HOUR ASC